[workspace]
members = [
    "myfavfiles",
    "myfavfiles_api",
    "myfavfiles_common",
    "myfavfiles_frontend",
]

[workspace.dependencies]
axum = "0.5.16"

[workspace.dependencies.tokio]
version = "1.18.5"
features = ["full"]

