[package]
name = "myfavfiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
envy = "0.4.2"
actix-web = "4.0.0-rc.3"
actix-files = "0.6.0-beta.16"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
env_logger = "0.9.0"

[dependencies.sea-orm]
version = "0.6.0"
default-features = false
features = ["sqlx-postgres", "runtime-actix-native-tls", "macros"]
