[tasks.create-dev]
command = "podman"
args = [
    "create", "--name=myfavfiles-pg", "-e=POSTGRES_PASSWORD=password",
    "-p=5432:5432",
    "postgres",
]

[tasks.run-dev]
command = "podman"
args = ["start", "myfavfiles-pg"]

[tasks.stop-dev]
command = "podman"
args = ["stop", "myfavfiles-pg"]

[tasks.rm-dev]
command = "podman"
args = ["rm", "-f", "myfavfiles-pg"]

[tasks.create-db]
command = "sqlx"
args = ["database", "create"]

[tasks.migrate-db]
command = "sqlx"
args = ["migrate", "run"]

[tasks.delete-entities]
command = "rm"
args = ["-rf", "./src/entities"]

[tasks.generate-entities]
command = "sea-orm-cli"
args = ["generate", "entity", "-o=./src/entities"]

[tasks.update-entities]
run_task = [
    { name = "generate-entities" },
    { name = "delete-entities" },
]
