[package]
name = "myfavfiles_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envy = "0.4.2"
axum = "0.5.0"
dotenv = "0.15.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]
